version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      #dev-id
      #- aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 774025244507.dkr.ecr.us-west-2.amazonaws.com
      #prod-id
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 534030821312.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=534030821312.dkr.ecr.us-east-1.amazonaws.com/pet1
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"cb-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
